# Роля на модула: Тънък adapter, който подава semantic layout към PPTX renderer-а.
# Чети коментарите като обяснение на причината за кода и връзката му със следващия слой, а не като буквален превод на Python синтаксиса.
from pathlib import Path

from app.semantic.contracts import LayoutedPresentationDocument, ThemeDefinition
from app.services.exporters.base import BaseExporter
from app.services.layout_engine import build_pptx_presentation

# `BACKEND_DIR` пази резултата от `Path(__file__).resolve`, за да бъде проверен или използван в следващите стъпки вместо операцията да се повтори.
BACKEND_DIR = Path(__file__).resolve().parents[3]
# `OUTPUT_DIR` е общата директория за крайни PPTX/PDF файлове, която едновременно се използва от exporters и се публикува като static route.
OUTPUT_DIR = BACKEND_DIR / "generated"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


class PptxExporter(BaseExporter):
    # Роля на класа: Класът групира общо състояние и операции, които принадлежат на една pipeline отговорност.
    # Методите получават `self`, затова могат да споделят конфигурация и кеширани ресурси без глобални променливи.
    """
    Native PPTX exporter that maps the JSON model directly to editable PowerPoint elements.
    """

    def export_pptx(self, presentation: LayoutedPresentationDocument, theme: ThemeDefinition, asset_id: str) -> str:
        # Роля в pipeline-а: превръща готовия layout в краен файл за клиента.
        # Входът идва през `self` (неуточнен тип), `presentation` (LayoutedPresentationDocument), `theme` (ThemeDefinition), `asset_id` (str); имената показват каква част от контекста е собственост на тази стъпка.
        # Основните преходи навън са към `build_pptx_presentation`, `deck.save`; така се вижда кои отговорности функцията делегира.
        # Типовете в сигнатурата документират договора за caller-а и позволяват грешки да се хващат преди runtime.
        # Изходен договор: `str`. Резултатът е част от последния rendering/export етап и вече е близо до крайния PPTX/PDF файл.
        output_name = f"{asset_id}.pptx"
        # `output_path` е крайното място във файловата система, което следващият слой може безопасно да използва.
        output_path = OUTPUT_DIR / output_name

        # `deck` пази резултата от `build_pptx_presentation`, за да бъде проверен или използван в следващите стъпки вместо операцията да се повтори.
        deck = build_pptx_presentation(presentation, theme)
        deck.core_properties.title = presentation.title
        deck.core_properties.subject = "AuraSlidesAi Presentation"
        deck.core_properties.author = "AuraSlidesAi"

        deck.save(output_path)
        return output_name

    def export_pdf(self, presentation: LayoutedPresentationDocument, theme: ThemeDefinition, asset_id: str) -> str:
        # For Native export, PDF is often generated by converting the PPTX or using an HTML intermediate.
        # This will be implemented in PdfExporter specifically or dispatcher.
        # Роля в pipeline-а: превръща готовия layout в краен файл за клиента.
        # Входът идва през `self` (неуточнен тип), `presentation` (LayoutedPresentationDocument), `theme` (ThemeDefinition), `asset_id` (str); имената показват каква част от контекста е собственост на тази стъпка.
        # Основните преходи навън са към `NotImplementedError`; така се вижда кои отговорности функцията делегира.
        # Типовете в сигнатурата документират договора за caller-а и позволяват грешки да се хващат преди runtime.
        # Изходен договор: `str`. Резултатът е част от последния rendering/export етап и вече е близо до крайния PPTX/PDF файл.
        raise NotImplementedError("Use PdfExporter for PDF output.")
