from pathlib import Path

from app.semantic.contracts import LayoutedPresentationDocument, ThemeDefinition
from app.services.layout_engine import build_pptx_presentation
from app.services.exporters.base import BaseExporter

BACKEND_DIR = Path(__file__).resolve().parents[3]
OUTPUT_DIR = BACKEND_DIR / "generated"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

class PptxExporter(BaseExporter):
    """
    Native PPTX exporter that maps the JSON model directly to editable PowerPoint elements.
    """
    
    def export_pptx(self, presentation: LayoutedPresentationDocument, theme: ThemeDefinition, asset_id: str) -> str:
        output_name = f"{asset_id}.pptx"
        output_path = OUTPUT_DIR / output_name
        
        deck = build_pptx_presentation(presentation, theme)
        deck.core_properties.title = presentation.title
        deck.core_properties.subject = "AuraSlidesAi Presentation"
        deck.core_properties.author = "AuraSlidesAi"
        
        deck.save(output_path)
        return output_name

    def export_pdf(self, presentation: LayoutedPresentationDocument, theme: ThemeDefinition, asset_id: str) -> str:
        # For Native export, PDF is often generated by converting the PPTX or using an HTML intermediate.
        # This will be implemented in PdfExporter specifically or dispatcher.
        raise NotImplementedError("Use PdfExporter for PDF output.")
